name: "Wallos (Web UI)"
slug: "wallos"
version: "0.2.2"
description: "Wallos: self-hosted subscription/expense tracker (wraps bellamy/wallos Docker image)."
url: "https://wallosapp.com/"
changelog: "https://github.com/ellite/Wallos/releases/tag/v{version}"
arch:
  - amd64
  - aarch64
startup: "application"
init: false
stage: "stable"
ingress: false
panel_icon: "mdi:wallet"
webui: "http://[HOST]:[PORT:80]/"
ports:
  "80/tcp": 8282
ports_description:
  "80/tcp": "Wallos Web UI (host port editable)"
map:
  - type: addon_config
    read_only: false
    path: /var/www/html/db
options:
  TZ: "Europe/Vilnius"
  APP_URL: ""
schema:
  TZ: str
  APP_URL: str?
