---
name: "Wallos"
version: "3.3.0"
slug: wallos
description: "Self-hosted personal subscription tracker (Wallos)"
url: "https://github.com/ellite/Wallos"

startup: services
boot: auto

arch:
  - amd64
  - aarch64

image: "ghcr.io/ellite/wallos:3.3.0"

map:
  - addon_config:rw

init: run.sh

ingress: true
ingress_port: 80

ports:
  "80/tcp": 80
