name: "Wallos (Web UI)"
slug: "wallos"
version: "0.2.0"
description: "Wallos: self-hosted subscription/expense tracker (wraps bellamy/wallos Docker image)."
url: "https://wallosapp.com/"
arch:
  - amd64
  - aarch64
startup: "application"
init: false
stage: "stable"
ingress: false
panel_icon: "mdi:wallet"
# IMPORTANT: Use the container port in [PORT:<container>], HA will substitute the mapped host port
webui: "http://[HOST]:[PORT:80]/"
ports:
  "80/tcp": 8282
ports_description:
  "80/tcp": "Wallos Web UI (host port editable)"
map:
  - type: addon_config
    read_only: false
    path: /config
options:
  TZ: "Europe/Vilnius"
  APP_URL: ""
schema:
  TZ: str
  APP_URL: str?
