---
name: "Wallos"
version: "3.3.0"
slug: wallos
description: "Self-hosted personal subscription tracker (Wallos)"
url: "https://github.com/ellite/Wallos"
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:80]
init: false
arch:
  - aarch64
  - amd64
map:
  - addon_config:rw
  - share:rw
  - media:rw
ports:
  80/tcp: 80