name: "Wallos"
version: "1.0.0"
slug: "wallos"
description: "Self-hosted personal subscription tracker (Wallos)"
url: "https://github.com/ellite/Wallos"

startup: services
boot: auto

arch:
  - amd64
  - aarch64

host_network: false

# Expose the built-in Web UI via Ingress
ingress: true
ingress_port: 80

# Persist everything under /config
map:
  - config:rw

# Run our init hook to symlink /config into the container,
# then exit so the image's own ENTRYPOINT starts Wallos.
init: run.sh