name: "Wallos"
version: "1.0.0"
slug: "wallos"
description: "Self-hosted personal subscription tracker (Wallos)"
url: "https://github.com/ellite/Wallos"
startup: services
boot: auto

arch:
  - amd64
  - aarch64

host_network: false

ingress: true
ingress_port: 80

map:
  - config:rw

init: false

image: bellamy/wallos:latest
