name: "Wallos (Web UI)"
slug: "wallos"
version: "0.1.1"
description: "Wallos: self-hosted subscription/expense tracker (wraps bellamy/wallos Docker image)."
url: "https://wallosapp.com/"
arch:
  - amd64
  - aarch64
image: "ghcr.io/mindogo1/ha-addon-wallos"
startup: "application"
init: false
stage: "stable"
ingress: false
panel_icon: "mdi:wallet"
webui: "http://[HOST]:[PORT:8282]/"
ports:
  "8282/tcp": 8282
ports_description:
  "8282/tcp": "Wallos Web UI"
map:
  - type: addon_config
    read_only: false
    path: /config
options:
  TZ: "Europe/Vilnius"
  APP_URL: ""
schema:
  TZ: str
  APP_URL: str?
