# Cleanuparr Home Assistant Addon Configuration
#
# This file defines the default configuration options for the Cleanuparr addon.
# You can modify these values via the Home Assistant Add-on UI.

log_level: Information # Set the logging verbosity: Trace, Debug, Information, Warning, Error, Critical, None
paths_to_cleanup: # A list of directories Cleanuparr should scan.
  # IMPORTANT: These paths must correspond to paths accessible WITHIN the Docker container.
  # For common Home Assistant shared directories, use `/share`, `/media`, etc.
  # Example:
  # - /share/downloads/incomplete
  # - /media/tv/series/.grab
dry_run: true # Set to 'true' to simulate cleanup without deleting files. ALWAYS test with dry_run first!