name: "AURA (Mediux)"
slug: "aura"
# This will be auto-bumped by the workflow below to match upstream version.json
version: "0.0.0"
description: "AURA — use Mediux image sets with Plex/Emby/Jellyfin."
url: "https://mediux-team.github.io/AURA/"
changelog: "https://github.com/mediux-team/AURA/commits/master"
arch:
  - amd64
  - aarch64
startup: "application"
init: false
stage: "stable"
panel_icon: "mdi:image-auto-adjust"
webui: "http://[HOST]:[PORT:3000]/"

# Expose AURA's ports (UI 3000, optional internal API 8888)
ports:
  "3000/tcp": 3000
  "8888/tcp": 8888
ports_description:
  "3000/tcp": "Web UI (AURA)"
  "8888/tcp": "AURA API (optional)"

map:
  # Persist AURA configuration (/config inside container)
  - type: addon_config
    read_only: false
    path: /config
  # Give AURA access to your HA /media for 'Save image next to content'
  - media:rw

# Optional cosmetic/envs (AURA mostly configures itself via /config/config.yaml)
options:
  TZ: "Europe/Vilnius"
schema:
  TZ: str?
