name: "AURA (Mediux)"
slug: "aura"
version: "0.0.0"
description: "AURA — use Mediux image sets with Plex/Emby/Jellyfin."
url: "https://github.com/mediux-team/AURA"
changelog: "https://github.com/mediux-team/AURA/commits/master"

arch:
  - amd64
  - aarch64

startup: application
init: false
stage: stable
panel_icon: mdi:image-auto-adjust

# Use upstream image so its entrypoint starts normally
image: "ghcr.io/mediux-team/aura:latest"

# AURA listens on 3000 in the container; map to a free host port (3101)
webui: "http://[HOST]:[PORT:3000]/"
ports:
  "3000/tcp": 3101
ports_description:
  "3000/tcp": "Web UI (AURA)"

# Persist settings and allow saving beside media
map:
  - addon_config:rw
  - media:rw

options:
  TZ: "Europe/Vilnius"
schema:
  TZ: str?
