name: "AURA (Mediux)"
slug: "aura"
version: "0.0.0"
description: "AURA — use Mediux image sets with Plex/Emby/Jellyfin."
url: "https://mediux-team.github.io/AURA/"
changelog: "https://github.com/mediux-team/AURA/commits/master"

arch:
  - amd64
  - aarch64

startup: application
init: false
stage: stable
panel_icon: mdi:image-auto-adjust

# Use upstream prebuilt image so its entrypoint runs as intended
image: "ghcr.io/mediux-team/aura:latest"

# AURA listens on 3000 in the container; map to any free HOST port (e.g., 3101)
webui: "http://[HOST]:[PORT:3000]/"
ports:
  "3000/tcp": 3101

# Keep it simple/valid: classic map syntax
map:
  - config:rw
  - media:rw

# Optional cosmetics
options:
  TZ: "Europe/Vilnius"
schema:
  TZ: str?
