name: "AURA (Mediux)"
slug: "aura"
version: "v0.9.27"
description: "AURA — use Mediux image sets with Plex/Emby/Jellyfin."
url: "https://mediux-team.github.io/AURA/"
changelog: "https://github.com/mediux-team/AURA/commits/master"

arch:
  - amd64
  - aarch64

startup: "application"
init: false
stage: "stable"
panel_icon: "mdi:image-auto-adjust"

webui: "http://[HOST]:[PORT:3000]/"

# host 3101 → container 3000 (AURA UI). Remove 8888 if unused.
ports:
  "3000/tcp": 3101
  "8888/tcp": 8888
ports_description:
  "3000/tcp": "Web UI (AURA)"
  "8888/tcp": "AURA API (optional)"

map:
  - type: addon_config
    read_only: false
    path: /config
  - media:rw

options:
  TZ: "Europe/Vilnius"
schema:
  TZ: str?
