name: "TitleCardMaker (v1 CLI)"
version: "0.4.1"
slug: "titlecardmaker"
description: "Automated title card maker for Plex/Jellyfin/Emby (v1). Wraps collinheist/titlecardmaker and exposes options via the add-on UI."
url: "https://titlecardmaker.com/"
arch:
  - amd64
image: "ghcr.io/mindogo1/ha-addon-titlecardmaker-{arch}"
startup: "application"
init: false
stage: "stable"
ingress: false
panel_icon: "mdi:format-title"
map:
  - type: addon_config
    read_only: false
    path: /config
  - type: media
    read_only: false
    path: /Media
options:
  TZ: "Europe/Vilnius"
  PLEX_URL: ""
  PLEX_TOKEN: ""
  SONARR_URL: ""
  SONARR_API_KEY: ""
  TMDB_API_KEY: ""
  SOURCE_DIR: "/config/source/"
  SERIES_YAML: "/config/yaml/sonarr_sync.yml"
  CARD_DIR: "/config/cards/"
  SONARR_DOWNLOADED_ONLY: true
  SONARR_MONITORED_ONLY: true
  TCM_RUNTIME: "22:00"
  TCM_FREQUENCY: "1d"
  TCM_LOG: "INFO"
  PUID: 1000
  PGID: 1000
schema:
  TZ: str
  PLEX_URL: str?
  PLEX_TOKEN: str?
  SONARR_URL: str?
  SONARR_API_KEY: str?
  TMDB_API_KEY: str?
  SOURCE_DIR: str
  SERIES_YAML: str
  CARD_DIR: str
  SONARR_DOWNLOADED_ONLY: bool?
  SONARR_MONITORED_ONLY: bool?
  TCM_RUNTIME: str?
  TCM_FREQUENCY: str?
  TCM_LOG: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)
  PUID: int?
  PGID: int?
