name: Build Wallos Add-on (GHCR multi-arch manifest)

on:
  push:
    branches: [ main ]
    paths:
      - 'wallos/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read version
        id: ver
        run: |
          python - <<'PY' >> $GITHUB_ENV
          import yaml
          d=yaml.safe_load(open('wallos/config.yaml'))
          print(f"VERSION={d['version']}")
          PY

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./wallos
          file: ./wallos/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ha-addon-wallos:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/ha-addon-wallos:latest
