name: Build All Home Assistant Addons

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC to check for Cleanuparr updates
  push:
    branches:
      - main # Trigger on pushes to your main branch
    paths:
      - '**' # Trigger if any file in the repo changes

jobs:
  # Job 1: Find all addon directories
  find_addons:
    runs-on: ubuntu-latest
    outputs:
      addons: ${{ steps.addon_list.outputs.addons }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get addon list
        id: addon_list
        run: |
          ADDONS=$(find . -maxdepth 2 -type f -name "addon.json" -printf '%h\n' | sed 's|./||' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "Found addon directories: $ADDONS"
          echo "addons=${ADDONS}" >> "$GITHUB_OUTPUT"

  # Job 2: Build and push each addon for each architecture using a matrix
  build_and_push:
    needs: find_addons
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        addon_dir: ${{ fromJson(needs.find_addons.outputs.addons) }}
        # REMOVED "armv7" from the list below
        arch: [amd64, aarch64]
        include:
          - arch: amd64
            platform: linux/amd64
          - arch: aarch64
            platform: linux/arm64
          # REMOVED the armv7 include block
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read addon.json for ${{ matrix.addon_dir }}
        id: addon_info
        run: |
          ADDON_SLUG=$(jq -r '.slug' "${{ matrix.addon_dir }}/addon.json")
          ADDON_VERSION=$(jq -r '.version' "${{ matrix.addon_dir }}/addon.json")
          echo "addon_slug=$ADDON_SLUG" >> "$GITHUB_OUTPUT"
          echo "addon_version=$ADDON_VERSION" >> "$GITHUB_OUTPUT"

      - name: Build and push ${{ matrix.addon_dir }} for ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: "./${{ matrix.addon_dir }}"
          file: "./${{ matrix.addon_dir }}/Dockerfile"
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ steps.addon_info.outputs.addon_slug }}-${{ matrix.arch }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ steps.addon_info.outputs.addon_slug }}-${{ matrix.arch }}:${{ steps.addon_info.outputs.addon_version }}
          build-args: BUILD_FROM=ghcr.io/home-assistant/${{ matrix.arch }}-base:latest