name: Validate version on tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure config.yaml version matches tag
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          PY=$(cat <<'PY'
import yaml,sys
d=yaml.safe_load(open('titlecardmaker/config.yaml'))
print(d['version'])
PY
          )
          CFG=$(python - << "$PY")
          echo "Tag: $TAG, Config version: $CFG"
          if [ "$TAG" != "$CFG" ]; then
            echo "::error::Tag ($TAG) does not match config.yaml version ($CFG)"
            exit 1
          fi
