name: Update ByteStash Version

permissions:
  contents: write

on:
  schedule:
    - cron: '0 4 * * *'   # daily at 04:00 UTC
  workflow_dispatch: {}

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Fetch latest ByteStash release tag
        id: get_tag
        run: |
          set -e
          tag=$(curl -s \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/jordan-dalby/ByteStash/releases/latest \
            | jq -r .tag_name | sed 's/^v//')
          [ -n "$tag" ] && [ "$tag" != "null" ]
          echo "Latest tag: $tag"
          echo "VERSION=$tag" >> $GITHUB_ENV

      - name: Sanity check target file
        run: |
          set -e
          F="bytestash/config.yaml"
          test -f "$F"
          # ensure this really is the add-on config (not a workflow file)
          if ! grep -q '^slug:[[:space:]]*bytestash$' "$F"; then
            echo "::error::$F does not look like the add-on config (missing 'slug: bytestash')."
            echo "First 40 lines for debugging:"
            sed -n '1,40p' "$F"
            exit 1
          fi

      - name: Bump version in config.yaml (safe, no duplicates)
        run: |
          set -e
          F="bytestash/config.yaml"
          awk -v V="$VERSION" '
            BEGIN{seen=0}
            /^version:[[:space:]]*/{
              if (!seen) { print "version: \"" V "\""; seen=1; next }
              else { next }  # drop duplicates
            }
            { print }
          ' "$F" > "$F.tmp" && mv "$F.tmp" "$F"

      - name: Ensure upstream changelog line exists
        run: |
          set -e
          F="bytestash/config.yaml"
          if grep -q '^changelog:' "$F"; then
            sed -i 's|^changelog:.*|changelog: "https://github.com/jordan-dalby/ByteStash/releases/tag/v{version}"|' "$F"
          else
            sed -i '1ichangelog: "https://github.com/jordan-dalby/ByteStash/releases/tag/v{version}"' "$F"
          fi

      - name: Commit & push version bump
        run: |
          set -e
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'actions@github.com'
            git add bytestash/config.yaml
            git commit -m "chore(bytestash): bump to $VERSION"
            git push
          else
            echo "No changes."
          fi