name: Update Wallos Version

permissions:
  contents: write

on:
  schedule:
    - cron: '0 5 * * *'     # daily at 05:00 UTC
  workflow_dispatch: {}

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Fetch latest Wallos release tag
        id: get_tag
        run: |
          set -e
          RAW_TAG=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ellite/Wallos/releases/latest \
            | jq -r .tag_name)
          [ -n "$RAW_TAG" ] && [ "$RAW_TAG" != "null" ]
          VERSION="${RAW_TAG#v}"
          echo "RAW_TAG=$RAW_TAG" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Latest tag: $RAW_TAG (version: $VERSION)"

      - name: Bump version in config.yaml (safe, no duplicates)
        run: |
          set -e
          F="wallos/config.yaml"
          awk -v V="$VERSION" '
            BEGIN{seen=0}
            /^version:[[:space:]]*/{
              if (!seen) { print "version: \"" V "\""; seen=1; next }
              else { next }
            }
            { print }
          ' "$F" > "$F.tmp" && mv "$F.tmp" "$F"

      - name: Upsert changelog with exact upstream tag URL
        run: |
          set -e
          F="wallos/config.yaml"
          if grep -q '^changelog:' "$F"; then
            sed -i 's|^changelog:.*|changelog: "https://github.com/ellite/Wallos/releases/tag/'"$RAW_TAG"'"|' "$F"
          else
            sed -i '1ichangelog: "https://github.com/ellite/Wallos/releases/tag/'"$RAW_TAG"'"' "$F"
          fi

      - name: Commit & push version bump
        run: |
          set -e
          git config --global user.name 'github-actions'
