name: Update Wallos Version

on:
  schedule:
    - cron: "0 5 * * *"   # daily 05:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Ensure jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch latest Wallos release tag
        id: get_tag
        run: |
          set -euo pipefail
          TAG=$(curl -fsSL https://api.github.com/repos/ellite/Wallos/releases/latest \
            | jq -r .tag_name | sed 's/^v//')
          if [ -z "$TAG" ] || [ "$TAG" = "null" ]; then
            echo "No release tag found"; exit 1
          fi
          echo "version=$TAG" >> "$GITHUB_OUTPUT"

      - name: Update config.yaml (version + changelog)
        run: |
          set -euo pipefail
          F="wallos/config.yaml"
          # bump/insert version (quoted)
          sed -i -E "s/^version:\s*\".*\"/version: \"${{ steps.get_tag.outputs.version }}\"/; t; \
            /^version:/! s/^/version: \"${{ steps.get_tag.outputs.version }}\"\n&/" "$F"
          # upsert changelog pointing to upstream
          if grep -q '^changelog:' "$F"; then
            sed -i -E 's|^changelog:.*|changelog: "https://github.com/ellite/Wallos/releases/tag/v{version}"|' "$F"
          else
            sed -i '1 a changelog: "https://github.com/ellite/Wallos/releases/tag/v{version}"' "$F"
          fi
          echo "Updated $F to version ${{ steps.get_tag.outputs.version }}"

      # --- Choose ONE of the push methods below ---

      # A) Direct push (works if your repo allows actions to push directly)
      - name: Commit & push (only if changed)
        if: ${{ !secrets.PAT_PUSH }}
        run: |
          set -e
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add wallos/config.yaml
            git commit -m "chore(wallos): bump to ${{ steps.get_tag.outputs.version }}"
            git push
          else
            echo "No changes."
          fi

      # B) Push via Personal Access Token (use if direct push fails / branch protected).
      #    Create a repo secret named PAT_PUSH with a token that has 'contents: write'.
      - name: Commit & push via PAT (only if changed)
        if: ${{ secrets.PAT_PUSH }}
        env:
          PAT: ${{ secrets.PAT_PUSH }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          set -e
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add wallos/config.yaml
            git commit -m "chore(wallos): bump to ${{ steps.get_tag.outputs.version }}"
            git remote set-url origin https://x-access-token:${PAT}@github.com/${OWNER}/${REPO}.git
            git push origin HEAD:${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}
          else
            echo "No changes."
          fi