name: Update Cleanuparr Base Image

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Pull latest upstream image
        run: |
          docker pull ghcr.io/cleanuparr/cleanuparr:latest
          echo "Image pulled."

      - name: Commit and push if updated
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git diff --cached --quiet || git commit -m "Update Cleanuparr base image"
          git push
