name: Update Tracktor Version

permissions:
  contents: write

on:
  schedule:
    - cron: "22 4 * * *"   # daily at 04:22 UTC
  workflow_dispatch: {}

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Fetch latest Tracktor release tag
        id: get_tag
        run: |
          set -e
          tag=$(curl -s -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/javedh-dev/tracktor/releases/latest \
            | jq -r .tag_name)
          if [ -z "$tag" ] || [ "$tag" = "null" ]; then
            echo "No release tag found; exiting without change."
            exit 0
          fi
          echo "VERSION=$tag" >> $GITHUB_ENV
          echo "Latest tag: $tag"

      - name: Bump version in tracktor/config.yaml (safe; drop duplicates)
        if: env.VERSION != ''
        run: |
          set -e
          F="tracktor/config.yaml"
          awk -v V="$VERSION" '
            BEGIN{seen=0}
            /^version:[[:space:]]*/{
              if (!seen) { print "version: \"" V "\""; seen=1; next }
              else { next }
            }
            { print }
          ' "$F" > "$F.tmp" && mv "$F.tmp" "$F"

      - name: Commit & push version bump
        if: env.VERSION != ''
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add tracktor/config.yaml
          git diff --cached --quiet || git commit -m "chore(tracktor): bump to $VERSION"
          git push
