name: Update ByteStash Version

on:
  schedule:
    - cron: "7 4 * * *"     # daily 04:07 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Ensure jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch latest ByteStash release tag
        id: get_tag
        run: |
          set -euo pipefail
          TAG=$(curl -fsSL https://api.github.com/repos/jordan-dalby/ByteStash/releases/latest \
            | jq -r .tag_name | sed 's/^v//')
          if [ -z "$TAG" ] || [ "$TAG" = "null" ]; then
            echo "No release tag found"; exit 1
          fi
          echo "version=$TAG" >> "$GITHUB_OUTPUT"

      - name: Update config.yaml (version + changelog)
        run: |
          set -euo pipefail
          F="bytestash/config.yaml"
          # bump/insert version (quoted)
          sed -i -E "s/^version:\s*\".*\"/version: \"${{ steps.get_tag.outputs.version }}\"/; t; \
            /^version:/! s/^/version: \"${{ steps.get_tag.outputs.version }}\"\n&/" "$F"
          # upsert changelog
          if grep -q '^changelog:' "$F"; then
            sed -i -E 's|^changelog:.*|changelog: "https://github.com/jordan-dalby/ByteStash/releases/tag/v{version}"|' "$F"
          else
            sed -i '1 a changelog: "https://github.com/jordan-dalby/ByteStash/releases/tag/v{version}"' "$F"
          fi
          echo "Updated $F to version ${{ steps.get_tag.outputs.version }}"

      - name: Commit & push (only if changed)
        run: |
          set -e
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add bytestash/config.yaml
            git commit -m "chore(bytestash): bump to ${{ steps.get_tag.outputs.version }}"
            git push
          else
            echo "No changes."
          fi