name: Update AURA Version

permissions:
  contents: write

on:
  schedule:
    - cron: '7 4 * * *'   # daily 04:07 UTC
  workflow_dispatch: {}

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get upstream version.json
        id: getver
        run: |
          set -e
          # Try master first; fall back to main just in case
          for BR in master main; do
            URL="https://raw.githubusercontent.com/mediux-team/AURA/${BR}/version.json"
            if curl -fsSL "$URL" -o /tmp/version.json; then
              break
            fi
          done
          jq -r .version /tmp/version.json | tee /tmp/VERSION
          echo "VERSION=$(cat /tmp/VERSION)" >> $GITHUB_ENV

      - name: Show current & new versions
        run: |
          CUR=$(awk -F'"' '/^version:/ {print $2; exit}' aura/config.yaml || echo "0.0.0")
          echo "Current config.yaml version: $CUR"
          echo "Upstream version.json: $VERSION"

      - name: Update config.yaml version (only first occurrence)
        run: |
          set -e
          F="aura/config.yaml"
          awk -v V="$VERSION" '
            BEGIN{done=0}
            /^version:[[:space:]]*"/ && done==0 { print "version: \"" V "\""; done=1; next }
            { print }
          ' "$F" > "$F.tmp"
          mv "$F.tmp" "$F"

      - name: Commit & push if changed
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add aura/config.yaml
          git diff --cached --quiet || git commit -m "chore(aura): bump to ${VERSION}"
          git push
