name: Update TitleCardMaker Version

permissions:
  contents: write

on:
  schedule:
    - cron: '30 4 * * *'   # daily 04:30 UTC
  workflow_dispatch: {}

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Fetch latest TitleCardMaker release tag
        id: get_tag
        run: |
          set -e
          RAW_TAG=$(curl -s \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/CollinHeist/TitleCardMaker/releases/latest \
            | jq -r .tag_name)
          [ -n "$RAW_TAG" ] && [ "$RAW_TAG" != "null" ]
          VERSION="latest-${RAW_TAG#v}"
          echo "RAW_TAG=$RAW_TAG" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Will set add-on version to: $VERSION"

      - name: Locate config.yaml (tcm-webui/ or titlecardmaker/)
        id: path
        run: |
          set -e
          if [ -f "tcm-webui/config.yaml" ]; then
            echo "CFG=tcm-webui/config.yaml" >> $GITHUB_OUTPUT
          elif [ -f "titlecardmaker/config.yaml" ]; then
            echo "CFG=titlecardmaker/config.yaml" >> $GITHUB_OUTPUT
          else
            echo "::error::No TitleCardMaker add-on config.yaml found (tcm-webui/ or titlecardmaker/)"
            exit 1
          fi

      - name: Sanity check (don’t mangle wrong file)
        run: |
          set -e
          F="${{ steps.path.outputs.CFG }}"
          test -f "$F"
          grep -qi 'TitleCardMaker' "$F" || {
            echo "::error::$F does not look like the TitleCardMaker add-on config."
            sed -n '1,60p' "$F"
            exit 1
          }

      - name: Write version (safe; drop duplicates)
        run: |
          set -e
          F="${{ steps.path.outputs.CFG }}"
          awk -v V="$VERSION" '
            BEGIN{seen=0}
            /^version:[[:space:]]*/{
              if (!seen) { print "version: \"" V "\""; seen=1; next }
              else { next }
            }
            { print }
          ' "$F" > "$F.tmp" && mv "$F.tmp" "$F"

      - name: Upsert changelog (exact upstream URL)
        run: |
          set -e
          F="${{ steps.path.outputs.CFG }}"
          URL="https://github.com/CollinHeist/TitleCardMaker/releases/tag/${RAW_TAG}"
          if grep -q '^changelog:' "$F"; then
            sed -i 's|^changelog:.*|changelog: "'"$URL"'"|' "$F"
          else
            sed -i '1ichangelog: "'"$URL"'"' "$F"
          fi

      - name: Commit & push
        run: |
          set -e
          F="${{ steps.path.outputs.CFG }}"
          if [ -n "$(git status --porcelain "$F")" ]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'actions@github.com'
            git add "$F"
            git commit -m "chore(titlecardmaker): bump to ${VERSION}"
            git push
          else
            echo "No changes."
          fi