name: Update Tracktor Version

permissions:
  contents: write

on:
  schedule:
    - cron: "22 4 * * *"   # daily at 04:22 UTC
  workflow_dispatch: {}

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch latest Tracktor release tag
        id: get_tag
        run: |
          set -e
          tag=$(curl -s -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/javedh-dev/tracktor/releases/latest \
            | jq -r .tag_name)
          if [ -z "$tag" ] || [ "$tag" = "null" ]; then
            echo "No release tag found; exiting."
            exit 0
          fi
          echo "VERSION=$tag" >> $GITHUB_ENV
          echo "Latest tag: $tag"

      - name: Bump version in config.yaml (safe; drop dups)
        if: env.VERSION != ''
        run: |
          set -e
          F="tracktor/config.yaml"
          awk -v V="$VERSION" '
            BEGIN{seen=0}
            /^version:[[:space:]]*/{
              if (!seen) { print "version: \"" V "\""; seen=1; next }
              else { next }
            }
            { print }
          ' "$F" > "$F.tmp" && mv "$F.tmp" "$F"

      - name: Pin Dockerfile to the same release
        if: env.VERSION != ''
        run: |
          set -e
          F="tracktor/Dockerfile"
          # replace an existing -b <something> clone to -b $VERSION
          sed -i -E "s|(git clone --depth=1)([^#]*)(-b[[:space:]]+)[^[:space:]]+([[:space:]]+https://github.com/javedh-dev/tracktor .*?)|\\1\\2\\3${VERSION}\\4|" "$F"
          # if no -b present, add it
          sed -i -E "s|git clone --depth=1 https://github.com/javedh-dev/tracktor \\.|git clone --depth=1 -b ${VERSION} https://github.com/javedh-dev/tracktor .|" "$F"

      - name: Commit & push
        run: |
          set -e
          if [ -n "$(git status --porcelain tracktor/)" ]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'actions@github.com'
            git add tracktor/config.yaml tracktor/Dockerfile
            git commit -m "chore(tracktor): bump to $VERSION"
            git push
          else
            echo "No changes."
          fi
