# .github/workflows/update-wallos.yml
name: Update Wallos Base Image

on:
  schedule:
    - cron: '0 3 * * *'  # daily at 03:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull latest Wallos image
        run: docker pull bellamy/wallos:latest

      - name: Commit bump if needed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add wallos/config.json
          git diff --cached --quiet || git commit -m "chore: update Wallos base image"
          git push
