name: Update Tracktor (edge)

permissions:
  contents: write

on:
  schedule:
    - cron: "22 4 * * *"   # daily 04:22 UTC
  workflow_dispatch: {}

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Probe default branch HEAD
        id: head
        run: |
          set -e
          repo="javedh-dev/tracktor"
          meta=$(curl -s -H "Accept: application/vnd.github+json" https://api.github.com/repos/$repo)
          def=$(echo "$meta" | jq -r .default_branch)
          commit=$(curl -s -H "Accept: application/vnd.github+json" https://api.github.com/repos/$repo/commits/$def)
          sha=$(echo "$commit" | jq -r .sha)
          sha7=$(echo "$sha" | cut -c1-7)
          date=$(date -u +%Y%m%d)
          echo "VERSION=edge-${date}-${sha7}" >> $GITHUB_ENV
          echo "CHANGELOG=https://github.com/$repo/commit/$sha" >> $GITHUB_ENV
          echo "Default: $def  SHA: $sha"

      - name: Write version in config.yaml (safe; drop dups)
        run: |
          set -e
          F="tracktor/config.yaml"
          awk -v V="$VERSION" '
            BEGIN{seen=0}
            /^version:[[:space:]]*/{
              if (!seen) { print "version: \"" V "\""; seen=1; next }
              else { next }
            }
            { print }
          ' "$F" > "$F.tmp" && mv "$F.tmp" "$F"

      - name: Upsert changelog to commit URL
        run: |
          set -e
          F="tracktor/config.yaml"
          if grep -q '^changelog:' "$F"; then
            sed -i 's|^changelog:.*|changelog: "'"$CHANGELOG"'"|' "$F"
          else
            sed -i '1ichangelog: "'"$CHANGELOG"'"' "$F"
          fi

      - name: Commit & push
        run: |
          set -e
          if [ -n "$(git status --porcelain tracktor/config.yaml)" ]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'actions@github.com'
            git add tracktor/config.yaml
            git commit -m "chore(tracktor): ${VERSION}"
            git push
          else
            echo "No changes."
          fi
