name: "AURA (Mediux)"
slug: "aura"
version: "0.0.0"                   # your repo version; updater can bump this later
description: "AURA — use Mediux image sets with Plex/Emby/Jellyfin."
url: "https://mediux-team.github.io/AURA/"
changelog: "https://github.com/mediux-team/AURA/commits/master"
arch:
  - amd64
  - aarch64
startup: application
init: false
stage: stable
panel_icon: mdi:image-auto-adjust

# Point the HA Web UI button at whatever host-side port maps to container 3000.
# [PORT:3000] automatically resolves to the host port you set below (e.g. 3101).
webui: "http://[HOST]:[PORT:3000]/"

# AURA listens on 3000 (UI) and optionally 8888 (API) inside the container.
# Map ONLY 3000 unless you plan to use the API.
ports:
  "3000/tcp": 3101       # change 3101 if you want a different host port
# ports_description is optional
ports_description:
  "3000/tcp": "Web UI (AURA)"

map:
  - type: addon_config
    read_only: false
    path: /config
  - media:rw                 # gives the container /media

# Pass HOST so AURA binds to all interfaces.
# (We’ll also handle /data/media below without replacing the image.)
options:
  TZ: "Europe/Vilnius"
  HOST: "0.0.0.0"
schema:
  TZ: str
  HOST: str?